### ISSUE TITLE
[FEATURE] Upgrade TinkerPop version to 3.5.2.

### ISSUE THREAD

**Issue by lyndonbauto** [aws/amazon-neptune-jdbc-driver#159]
Upgrade TinkerPop version to 3.5.2.

Currently it is 3.4.8 and this has issues with OpenJDK17 which some users are using.

**Comment by Cole-Greer** [comment]
Superseded by #230

**Comment by Cole-Greer** [comment]
TinkerPop has been upgraded to 3.6.4 with #230.
