### ISSUE TITLE
[FEATURE] Support WHERE and HAVING in conjunction with a JOIN clause

### ISSUE THREAD

**Issue by anchouls** [aws/amazon-neptune-jdbc-driver#175]
- [ ] **Have you validated that this is not currently reported in 
    [limitations](https://github.com/aws/amazon-neptune-jdbc-driver/blob/develop/sql-gremlin/README.asciidoc#sql-support-and-limitations) or
    [milestones](https://github.com/aws/amazon-neptune-jdbc-driver/milestones)? If so, please link it.**

## Feature Request Related to a Problem?
This problem is specified in [limitations/joins](https://github.com/aws/amazon-neptune-jdbc-driver/blob/develop/sql-gremlin/README.asciidoc#joins): `WHERE` and `HAVING` are not currently supported in conjunction with a `JOIN` clause

## Describe the Solution
According to the specification of the SQL language or its subset.

**Comment by Cole-Greer** [comment]
Closing as PR was previously accepted
