### ISSUE TITLE
Recieve null instead of ResultSet after calling getResultSet on PreparedStatement[BUG]

### ISSUE THREAD

**Issue by PavloPolovyi** [aws/amazon-neptune-jdbc-driver#235]
When executing cypher query(any) and using such a block of code to get ResultSet
```code
PreparedStatement statement = connection.prepareStatement(query)
if(statement.execute())
            resultSet = statement.getResultSet();
```
receive null instead of expected resultSet, but if I check in the evaluator of IDE statement has a non-empty ResultSet.

If instead use
```code
PreparedStatement statement = connection.prepareStatement(query)
ResultSet resultSet = statement.executeQuery();
```
resultSet is not empty and contains the expected result.

Platform: Windows 11
Java 8, driver 2.0.0-all

**Comment by Cole-Greer** [comment]
Resolved in #246
