### ISSUE TITLE
[BUG] openCypher and IAM doesn't refresh token

### ISSUE THREAD

**Issue by er1c** [aws/amazon-neptune-jdbc-driver#258]
## Describe the bug

When creating a jdbc connection via: `jdbc:neptune:opencypher://bolt://xxxxx.cluster-xxxxxus-east-1.neptune.amazonaws.com:8182;authScheme=IAMSigV4;serviceRegion=us-east-1`

If you 

- [x] **Have you validated that this is not currently reported in
    [SQL Support and Limitations](https://github.com/aws/amazon-neptune-jdbc-driver/blob/develop/markdown/sql-gremlin.md)?**

## Steps to Reproduce
- [x] **Is the JDBC Driver being used in a BI tool?**

    1. What vesion of the JDBC Driver are you using? 3.0.0
    2. What BI Tool are you using? DataGrip
    3. What version of the BI tool are you using? 2024.01
    4. What Java version are you using? 17
    5. Please provide steps to reproduce bug from initial launch of BI tool --- Leave connection open for > 5 minutes
    6. If bug occurred during query execution attach the SQL -- no
    7. Attach debug logs if applicable/possible (please ensure it doesn't contain any sensitive information) -- n/a

<img width="1000" alt="image" src="https://github.com/aws/amazon-neptune-jdbc-driver/assets/64685/750aecca-5e51-4455-bdbd-256fe6713bd1">

## Expected behavior

For use in a connection pool, I would expect to be able and re-use a connection for more than 5 minutes.

**Comment by Cole-Greer** [comment]
Hi @er1c, no token refreshing used to be a limitation of the bolt driver which is used under the hood. This limitation has since been addressed in [v5.14](https://github.com/neo4j/neo4j-java-driver/releases/tag/5.14.0), however neo4j-java-driver requires min java 17, where we are still supporting java 8.

**Comment by Cole-Greer** [comment]
This issue has been fixed in #259.
